### ISSUE TITLE
wrong message in logs when include-profile-specific-sources=false

### ISSUE THREAD

**Issue by jbkervyn** [spring-cloud/spring-cloud-kubernetes#1015]
**Describe the bug**
When setting the property include-profile-specific-sources=false, you still get a message in the log config-map with name : xxx-profiles not found in the namespace. 

**Sample**
This is purely cosmetic as the behavior of the system works as expected, but the message in the log is confusing

**Comment by wind57** [comment]
isn't that with `warn` level, though? It helps us understand issues when they are raised btw, that is why we need it.

**Comment by jbkervyn** [comment]
No, it's Info level. My understanding is that with the property is true, the app will look for confignames having names matching
- appName
- appName-profile1
- appName-profile2
- etc

With this property set to false, it should only look for an exact match. Therefore, I should not come up in the logs imho.

**Comment by wind57** [comment]
This has been fixed/updated in latest `main` branch, looks [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/ConfigUtils.java#L230..#L244).

We will be logging everything in `debug` mode only. imho, this ticket can be closed, but the code is not yet released...

**Comment by wind57** [comment]
@ryanjbaxter  mentioned in a PR that there are no plans to do one more release of the `2.1.x` branch, but this is not an issue anymore in the `3.0.x` (as I pointed out in the comment above), so, imho: this can be closed.

**Comment by ryanjbaxter** [comment]
We will release the 2.1.x branch but not 2.0.x

**Comment by wind57** [comment]
> We will release the 2.1.x branch but not 2.0.x

oh! thank you for this. 

---

I took a bit of time to look in the code to remember how it looks like in `2.1.x` branch and I don't understand how this would be possible. Both clients have such a check: `if (environment != null && includeProfileSpecificSources) { ... }` and only then we will be reading the profile based config map. 

@jbkervyn can you provide the exact version and logs that you use/see? Even better would be a minimal example for me to reproduce this issue, otherwise I can't do much here :(

**Comment by jbkervyn** [comment]
I can't reproduce it anymore. We are now using 2.1.3, and this looks fine there.

**Comment by wind57** [comment]
Lovely! Thank you for getting back
