### ISSUE TITLE
Support for multiple namespace

### ISSUE THREAD

**Issue by mehdikhelif** [spring-cloud/spring-cloud-kubernetes#1056]
Hello,

Currently there are two options: single namespace or all namespaces. For "security" reasons, we have a cluster setup where our service account cannot call cluster apis but only for a defined set of namespaces. However, our micro-services are running in different namespaces.

In the past we were overriding the fabric8 DiscoveryClient. When trying to move to spring-cloud-starter-kubernetes-client-loadbalancer we found that it was a bit more complicated to do. For instance SpringCloudKubernetesInformerFactoryProcessor class is not public and thus cannot be overridden.

I am not sure if the description is clear enough, but do you think such use case could be supported in the future ?
I am thinking to stick to fabric8 implementation, do you think this will still be maintained in near future ?

**Comment by wind57** [comment]
you mean you would like support for the discovery service per namespaces, right? What I mean is that you could specify the exact namespaces where you want services to be discovered, right? 

If so, I recall seeing this before and otherwise yes, it is on my TODO list. There is no ETA from my side (as I am just a contributor), but definitely something I will fix. It will go, though, in the `main` branch only, and this means it will be compatible with java-17 only. At least this is my plan, so far.

**Comment by wind57** [comment]
It seems this is the issue [here](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1000). so this is a duplicate of that one

**Comment by mehdikhelif** [comment]
Yes that is exactly what I would need. Some property like spring.cloud.kubernetes.discovery.namespaces

**Comment by wind57** [comment]
@ryanjbaxter this can be closed as a duplicate
