### ISSUE TITLE
fabric8 KubernetesDiscoveryClient filter is not fully working

### ISSUE THREAD

**Issue by luisalves00** [spring-cloud/spring-cloud-kubernetes#1182]
Using filter on version 2.1.5:

```yaml
spring:
    cloud:
        kubernetes:
            discovery:
                all-namespaces: true
                filter: "#root.metadata.namespace matches '^uat.*$'"
```

Will not work as expected because on

```java
   public interface DiscoveryClient extends Ordered {

	/**
	 * @return All known service IDs.
	 */
	List<String> getServices();
   }
```

the spec says to return the service IDs, but on the implementation (org.springframework.cloud.kubernetes.fabric8.discovery.KubernetesDiscoveryClient) it's returning service names:

```java
        @Override
	public List<String> getServices() {
		String spelExpression = this.properties.getFilter();
		Predicate<Service> filteredServices;
		if (spelExpression == null || spelExpression.isEmpty()) {
			filteredServices = (Service instance) -> true;
		}
		else {
			Expression filterExpr = this.parser.parseExpression(spelExpression);
			filteredServices = (Service instance) -> {
				Boolean include = filterExpr.getValue(this.evalCtxt, instance, Boolean.class);
				if (include == null) {
					return false;
				}
				return include;
			};
		}
		return getServices(filteredServices);
	}

	public List<String> getServices(Predicate<Service> filter) {
		return this.kubernetesClientServicesFunction.apply(this.client).list().getItems().stream().filter(filter)
				.map(s -> s.getMetadata().getName()).collect(Collectors.toList());
	}
```

which then will fail when we get the actual endpoints. because names might be the same across different namespaces:

```java
        @Override
	public List<ServiceInstance> getInstances(String serviceId) {
		Assert.notNull(serviceId, "[Assertion failed] - the object argument must not be null");

		List<EndpointSubsetNS> subsetsNS = this.getEndPointsList(serviceId).stream().map(this::getSubsetsFromEndpoints)
				.collect(Collectors.toList());

		List<ServiceInstance> instances = new ArrayList<>();
		if (!subsetsNS.isEmpty()) {
			for (EndpointSubsetNS es : subsetsNS) {
				instances.addAll(this.getNamespaceServiceInstances(es, serviceId));
			}
		}

		return instances;
	}

	public List<Endpoints> getEndPointsList(String serviceId) {
		return this.properties.isAllNamespaces()
				? this.client.endpoints().inAnyNamespace().withField("metadata.name", serviceId)
						.withLabels(properties.getServiceLabels()).list().getItems()
				: this.client.endpoints().withField("metadata.name", serviceId)
						.withLabels(properties.getServiceLabels()).list().getItems();
	}
```

This  **withField("metadata.name", serviceId)** is not a good idea as names are not unique.

I guess the solution is to return serviceIds instead of names or add the filtering strategy when retrieving the Endpoints.
From code is clear that ServiceLabels will work fine on getting the Endpoints.

**Comment by wind57** [comment]
imho, this functionality is in desperate need for some refactoring, and proper integration tests. I do have some other things in my list of to do things, but this one will receive a lot of my attention in the beginning of next year. just wanted to let you know.

**Comment by luisalves00** [comment]
@wind57 probably because not all the configuration requirements were clear when developed. A small refactor would help.

If you could replace the existing getServices() by

```
        List<Service> getServices();
```

then you'd have all info needed for actuators (service name, namespace and maybe other) and also the real serviceids that you could use on getInstances(String serviceId) and getEndPointsList(String serviceId).

**Comment by wind57** [comment]
Let me just make it clear what the problem is and just to get a confirmation from you, as this is my next TODO. Minor note, is that this will go into `3.x.x` releases. 

---

We have two namespaces : `a-uat` and `b`. In both of these namespaces there is a service `my-service`.  
You have such a configuration in place:

```
spring:
    cloud:
        kubernetes:
            discovery:
                all-namespaces: true
                filter: "#root.metadata.namespace matches '^uat.*$'"
```

and call: `KubernetesDiscoveryClient::getServices`. It will return a list with a single String : `[my-service]`. 

You then go and call `KubernetesDiscoveryClient::getInstances` with that `my-service` as input and this will return a List of `ServiceInstance`, that will be based on _both_ `a` and `b` namespaces; because we have no such filter in `getInstances`. This is the bug that you are presenting here, right? 

---

@ryanjbaxter that is of course fixable. I also agree that `KubernetesDiscoveryClient::getServices` should return the service ids, instead of names, such an information is available like this for example:

```
{
    "apiVersion": "v1",
    "kind": "Endpoints",
    "metadata": {
        "annotations": {
            "endpoints.kubernetes.io/last-change-trigger-time": "2023-03-06T07:47:11Z"
        },
        "creationTimestamp": "2023-03-06T07:47:11Z",
        "name": "busybox-service",
        "namespace": "default",
        "resourceVersion": "521193",
        "uid": "43e36d8a-8b86-4c44-9d56-07b3c50a4c99"
    }
```

Notice that `uid`...

But this means breaking changes, because we would not return service names... I mean, it's a bug, so to me, it should not matter. Waiting for your feedback here. thank you.

**Comment by ryanjbaxter** [comment]
I think we are confusing service id and instance id here.  A service id is the name of the service that is unique across the entire app architecture.  In the context of K8S that would mean `my-service` is the name of the service.  It is unique across namespaces and potentially across clusters.  However there will be multiple instances of that service, and that is where instance id comes in, it is the unique id of that service (in that architecture).  

`DiscoveryClient::getServices` just returns a list of service ids that are discoverable.  You can then pass one of those service ids to `getInsances` to get all the instances of that service.  A `uid` is an instance id not a service id.

To me the bug here appears to be that we are just not applying the same filter when retrieving the endpoints

**Comment by luisalves00** [comment]
@wind57 Exactly. 
@ryanjbaxter you might be correct. I still don't have much experience with K8s. What I know is that same service name can be across different namespaces. So a fully qualified name of a service would be <namespace>.<service-name>. 

What I've seen is that getServices() is returning a filtered list of names. So if I have service names "todo-service" in 10 namespaces the outcome will be a list with "todo-service" (we don't know the namespace).

Then as @wind57 pointed out if I get an instance of the service it can be on any namespace ignoring (filter: "#root.metadata.namespace matches '^uat.*$'"). I want only instances that match the filter so I can have multiple environments on the same K8s cluster. For what I've read is a common pattern and I think it was why this filter feature was requested.

**Comment by ryanjbaxter** [comment]
Correct when you call `getServices` all you know is the service name, you have no idea how many instances there may be (other than there is at least 1 instance) what namespace the services are in or what cluster they are in.  It is just telling you...here are the services that are currently available.  

To get more information about the specific service you need to call `getInstances`.  This will tell you all the details.  

I think the bug here is if you have a filter, the `getInstances` call returns all instance data and does not respect the filter.

**Comment by wind57** [comment]
I am confused and I'd like to debate this a bit more, to have a better understanding please. For example:

> It is unique across namespaces and potentially across clusters.

I can't see this being correct, unless you mean something that I (yet again!) do not fully grasp. How can it be unique, when all we do in `KubernetesDiscoveryClient::getServices` is get the client and search for k8s services. For simplicity let's say that we search with the option `all-namespaces=true`. Of course I can have:

- `my-service` in namespace `a`
- `my-service` in namespace `b`

I can't figure out what you mean that it will be unique. In the example above a call to `KubernetesDiscoveryClient::getServices` will result in `[my-service, my-service]`. May be we can improve here to begin with, and return no duplicates?

---

The second part with `instanceId` is where an example will make it simpler, let's say I have a busybox service with two replica pods. When calling `KubernetesDiscoveryClient::getInstances`, we will return two `ServiceInstance`s (simplified):

`first       : {serviceId = busybox-service, instanceId = 123}`
`second : {serviceId = busybox-service, instanceId = 456}`

where `123` and `456` are the `.metadata.uid` of the _pods_ that represent that service. 

This, in the end, boils down to how users are supposed to use this. I mean what are the real use-cases where this is used. 
I do not mind adding the filter and thus fixes this, I just want to understand better.

**Comment by luisalves00** [comment]
@wind57 for your first scenario if you add a filter that only matches namespace 'a' then the list will be [my-service]. I think there isn't not use case where it's interesting to fetch same service from multiple namespaces, because this would mean 2 different services with same name (different functionality) or same service but on different environments (environment segregation). Here I don't know if it's possible to return something that uniquely identifies the services (e.g: my-service@a).

On the second scenario the filter is for the same requirement I mention before. I want only pods that belong to my-service@a, as my-service@b is another environment (high probably) or another namespace with a service having the same name (low probability)

Deployment scenarios:
[Cluster per application](https://learnk8s.io/a/973fc59147c98118ebdd82c422bcd873.svg)
[One large shared cluster](https://learnk8s.io/a/8e08ddbc87c840c5bc28609eb59ce592.svg)

In my case we have we have a cluster where has multiple test environments.

**Comment by luisalves00** [comment]
@wind57 I get your point. Since filter is optional you are leaving the user to decide how they deploy their services. In my current case I end up with what you've pointed out: [my-service, my-service]. I could rename the services so the list has a single item. Something like 'a-my-service'. But this requires extra effort for CI/CD and now my service is DEV and PROD will not have the same name as the ones in QA environments. That's where the filter capability helps. I can keep same name on all clusters and apply the extra filtering so on QA environments I always get a single Service. I would even give a WARN log if we receive a list ('[my-service, my-service]'), as this is probably now what the developers want.

**Comment by wind57** [comment]
> as this is probably now what the developers want

EXACTLY! If I were the using fabric8-discovery, I would have to scratch my head twice to understand what a result in the for `[my-service, my-service]` would mean. A bug? Expected? Did I do something wrong here?

Anyway, we both agree on the same patterns here, I'll wait for Ryan to chime in, and once I agree with him, I will fix this one way or another.

**Comment by ryanjbaxter** [comment]
> I can't see this being correct, unless you mean something that I (yet again!) do not fully grasp. How can it be unique, when all we do in KubernetesDiscoveryClient::getServices is get the client and search for k8s services. For simplicity let's say that we search with the option all-namespaces=true. Of course I can have:
> 
> my-service in namespace a
> my-service in namespace b
> I can't figure out what you mean that it will be unique. In the example above a call to KubernetesDiscoveryClient::getServices will result in [my-service, my-service]. May be we can improve here to begin with, and return no duplicates?

Yes we should be returning duplicates of the same name, because they would be considered the same service.

> The second part with instanceId is where an example will make it simpler, let's say I have a busybox service with two replica pods. When calling KubernetesDiscoveryClient::getInstances, we will return two ServiceInstances (simplified):
> 
> first       : {serviceId = busybox-service, instanceId = 123}
> second : {serviceId = busybox-service, instanceId = 456}
> 
> where 123 and 456 are the .metadata.uid of the pods that represent that service.
> 
> This, in the end, boils down to how users are supposed to use this. I mean what are the real use-cases where this is used.
> I do not mind adding the filter and thus fixes this, I just want to understand better.

I agree the instance id itself is pretty much meaningless to the developer other than providing a way of uniquely identifying and instance.  However I don't think having 2 replicas in the same cluster in the same namespace is really all that interesting.

Whats more interesting is having two or more instances of `busybox-service` across multiple namespaces, say one in DEV and one in PROD.  Again the instance ids don't help you tell which namespace the service resides.  However we do have the `namespace` attribute as part of `KubernetesServiceInstance`
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-discovery/src/main/java/org/springframework/cloud/kubernetes/discovery/KubernetesServiceInstance.java#L46

This should help if we wanted to filter things to a specific namespace.  Or you could use it as a hint if you were using Spring Cloud LoadBalancer.  

But I still think the problem here is not filtering the endpoints, and that simple fix should fix the problem.

**Comment by wind57** [comment]
I started work on this one, but it's not as trivial as I hoped. The filter we have is based on the `Service`, while `getInstances` is based completely on the `Endpoints`. A filter that works for `Service` can easily be not applicable for an `Endpoints`. 

The only way to be safe is to query services also, when calling `getIntances` and then try to match `Endpoints::getName` with `Service::getName`. It's not complicated to achieve and I see no other alternative. Just a minor update.

**Comment by gls-luis-alves** [comment]
Sorry to disturb so long after the ticket is closed. I don't get how to make the filter work.
I have the catalog watch enabled (as I have @EnableScheduling) and on this line:

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/Fabric8EndpointsCatalogWatch.java#L45 

ALWAYS_TRUE is hardcoded

then here: https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-discovery/src/main/java/org/springframework/cloud/kubernetes/fabric8/discovery/Fabric8KubernetesDiscoveryClientUtils.java#L97

I end up always with "filter not present" and I got a filter but the ALWAYS_TRUE kinda ruins everything.

Why it's there in the first place?!

**Comment by luisalves00** [comment]
Sorry I took so long to answer. @wind57 you are correct. 
From my tests the feature is working as expected. When Feign Client is executed the filter is applied.
I think I was mislead by the catalog watcher. Why the filter is not applied there also? I guess it gets the whole catalog and later the filter is applied over it.

**Comment by luisalves00** [comment]
I'm not sure is needed. What is the purpose of the catalog watch? Update the discovery in the background? Would the filter still be applied when client does the call?

Also I think spring.cloud.kubernetes.discovery.catalog-services-watch.enabled=false doesn't work because the catalogServicesWatch doesn't exist in the configuration properties bean.

**Comment by luisalves00** [comment]
Maybe I'm wrong, I see it in https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c86e5f6ccb53cbbe5bb7532d86b57d80a1514bb2/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/discovery/ConditionalOnKubernetesCatalogEnabled.java#L38
But I was expecting it to be defined in https://github.com/spring-cloud/spring-cloud-kubernetes/blob/c86e5f6ccb53cbbe5bb7532d86b57d80a1514bb2/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/discovery/KubernetesDiscoveryProperties.java
