### ISSUE TITLE
Unable to start application that has kubernetes discovery flag disabled

### ISSUE THREAD

**Issue by driesdeproost** [spring-cloud/spring-cloud-kubernetes#1207]
**Describe the bug**
Since the introduction of [KubernetesCatalogWatchAutoConfiguration](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/catalog/KubernetesCatalogWatchAutoConfiguration.java) in 3.0.1 we can not start our application anymore.
The mentioned autoconfiguration will look for beans that we have not defined yet.

We are running our application on a kubernetes cluster, with discovery enabled, but kubernetes discovery disabled for now.

Since it is tied to discovery with `@ConditionalOnDiscoveryEnabled`, shouldn't the autoconfig get an extra condition `@ConditionalOnKubernetesDiscoveryEnabled` as well?

There were other autoconfigs introduced as well that might be impacted

**Comment by wind57** [comment]
Indeed it should be, and I thought it's not complicated to fix, but once I added unit tests, things broke somewhere else, so I need to spent some time figuring out what is going on. thx for raising this! and sorry for the issue - I made that change, so me to blame.

**Comment by wind57** [comment]
The problem I see when I add a test with `spring.cloud.kubernetes.discovery.enabled=false` and add `@ConditionalOnKubernetesDiscoveryEnabled` to the `KubernetesCatalogWatchAutoConfiguration`, is that the test fails:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kubernetesInformerDiscoveryClient' defined in class path resource [org/springframework/cloud/kubernetes/client/discovery/KubernetesDiscoveryClientAutoConfiguration$KubernetesInformerDiscoveryConfiguration.class]: Unsatisfied dependency expressed through method 'kubernetesInformerDiscoveryClient'
```

The issue the way I see it is that in our code we have : 

```
@ConditionalOnKubernetesDiscoveryEnabled
@EnableConfigurationProperties(KubernetesDiscoveryProperties.class)
public class KubernetesDiscoveryClientAutoConfiguration {
        @Configuration(proxyBeanMethods = false)
	@ConditionalOnBlockingDiscoveryEnabled
	public static class KubernetesInformerDiscoveryConfiguration {    
                  
                 @Bean
		@ConditionalOnMissingBean
		public KubernetesInformerDiscoveryClient kubernetesInformerDiscoveryClient(
				KubernetesNamespaceProvider kubernetesNamespaceProvider,
				CatalogSharedInformerFactory sharedInformerFactory, Lister<V1Service> serviceLister,
				Lister<V1Endpoints> endpointsLister, SharedInformer<V1Service> serviceInformer,
				SharedInformer<V1Endpoints> endpointsInformer, KubernetesDiscoveryProperties properties) {

                                 .... 


                }

        }
}
```

Because `@ConditionalOnKubernetesDiscoveryEnabled` is resolved to `false` in the _outer_ class `KubernetesDiscoveryClientAutoConfiguration`, it does not mean that it "inherited" to _inner_ class`KubernetesInformerDiscoveryConfiguration`. So spring still tried to create an instance of `KubernetesInformerDiscoveryClient`. 

it is kind of un-expected for me and I did not know that Spring acts like this. The proper way, imho, to fix this, is to refactor our code and get rid of the inner classes here (and in the future in all other places). @ryanjbaxter I hope my explanation makes sense here. wdyt?

**Comment by wind57** [comment]
This might be the root cause of another problem that we have, where we need to do things like:

```
// Injecting KubernetesDiscoveryProperties here would cause it to be
// initialized too early.
// Instead, get the all-namespaces property value from the Environment directly
boolean allNamespaces = environment.getProperty("spring.cloud.kubernetes.discovery.all-namespaces",
	Boolean.class, false);
```

I remember a recent case we were talking about, and I'll see if this is indeed the case

**Comment by ryanjbaxter** [comment]
What if you add `@ConditionalOnKubernetesDiscoveryEnabled` on the inner class?

**Comment by wind57** [comment]
It would work, yes; but then it under-covers another problem that we have. I'm preparing a PR where I'll present my case and we can discuss further if you do not mind

**Comment by wind57** [comment]
Now that I think about this a little, I am torn apart if this should really have the `@ConditionalOnKubernetesDiscoveryEnabled` :|

It would not change much if we add it, sure. But:

- if you do not want it to be picked-up, just add `spring.cloud.kubernetes.discovery.catalog-services-watch.enabled=false`
- you are pointing out to the kubernetes-native implementation of catalog watch, that came only in the `3.x.x` release. The fabric8 implementation, that existed before the kubernetes-native one, does _not_ have the  `@ConditionalOnKubernetesDiscoveryEnabled`. This is how it looks in `2.1.x` branch:

```
@Configuration(proxyBeanMethods = false)
@ConditionalOnDiscoveryEnabled
@ConditionalOnProperty(name = "spring.cloud.kubernetes.enabled", matchIfMissing = true)
@AutoConfigureAfter({ Fabric8AutoConfiguration.class })
public class KubernetesCatalogWatchAutoConfiguration {

	@Bean
	@ConditionalOnMissingBean
	@ConditionalOnProperty(name = "spring.cloud.kubernetes.discovery.catalog-services-watch.enabled",
			matchIfMissing = true)
	public KubernetesCatalogWatch kubernetesCatalogWatch(KubernetesClient client,
			KubernetesDiscoveryProperties properties) {
		return new KubernetesCatalogWatch(client, properties);
	}

}
```

I am more inclined towards not having it, this is not "discovery" per-se; especially since if we do add it now and someone has in their code : `spring.cloud.kubernetes.discovery.enabled=false`, they would not get this bean, and they would expect to. So this will be a breaking change in their configs. 

---

Your issue under-covered some other problems we have, but me, personally (and I am _not_ part of this team that decides such things), would not add it. @ryanjbaxter I need a sane advice here please... If we decide to add it, we need it in fabric8 auto-config also.

**Comment by ryanjbaxter** [comment]
Fair point but can we take a step back here...
What is the bean that is not being created when disabling kubernetes discovery?  How come that bean exists in the Fabric8 case?

**Comment by driesdeproost** [comment]
Hi @wind57 and @ryanjbaxter 

Thanks for jumping on the issue so quickly and sorry for my late reply. I was out of office for a few days :)

`Can you provide the exception and the details on the beans that are missing?`

For me it was the following:
Parameter 2 of method kubernetesCatalogWatch in org.springframework.cloud.kubernetes.client.discovery.catalog.KubernetesCatalogWatchAutoConfiguration required a bean of type 'org.springframework.cloud.kubernetes.commons.discovery.KubernetesDiscoveryProperties' that could not be found.

`if you do not want it to be picked-up, just add spring.cloud.kubernetes.discovery.catalog-services-watch.enabled=false`

Indeed, this is what we did in the end and we are unblocked for now :)

**Comment by driesdeproost** [comment]
good points by the way, @wind57

**Comment by wind57** [comment]
there are two different topics here now:

- fabric8, which I will tackle in the next PR, after my current one, so I propose to let it aside.
- current one. Since it fails for the OP with `KubernetesDiscoveryProperties` missing, the solution is rather simpler? a) do not add `@ConditionalOnKubernetesDiscoveryEnabled` to the `KubernetesCatalogWatchAutoConfiguration` b) add `@EnableConfigurationProperties(KubernetesDiscoveryProperties.class)`

To be honest, I did a lot more than this changes in my PR (ready within a couple of days), since there many other issues. But this specific one is much simpler. wdyt?

**Comment by ryanjbaxter** [comment]
Is this the only property we are using?
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/7c73c5b941cfa2bc494edde44b49cb657f50611b/spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/catalog/KubernetesCatalogWatch.java#L97

If so why not create a configuration properties for the catalog watch with that one property and eliminate the requirement for the discovery properties?  Really we are not using the discovery client at all in the catalog watch.

**Comment by wind57** [comment]
_currently_ we don't. what if we will in the future? I'd like to keep properties tied together.

**Comment by ryanjbaxter** [comment]
If its a property we want to use across multiple components maybe the property belongs in `KubernetesClientProperties`?

**Comment by wind57** [comment]
good point. But if we move it's a breaking change. So 2 PR's you have in mind? One that deprecates, one that moves?

**Comment by ryanjbaxter** [comment]
I think we can deprecate the property in `KubernetesDiscoveryProperties` and move it to `KubernetesClientProperties.  `KubernetesCatalogWatch` is not public so we can just change that constructor.  

We do need to account for the functionality depending on the old property though.  Maybe its best to use an `@Value` in the autoconfiguration for the old property, and check if it is set before using the new property.  That same should be done in the discovery client implementation as well.

**Comment by wind57** [comment]
While playing around with your suggestion, I had yet again a dilema. What we require in `KubernetesCatalogWatch` from `KubernetesDiscoveryProperties` is `useEndpointSlices` and it occurred to me that this one is not a _client_ property per-se, I don't think we can move it to `KubernetesClientProperties`; at least it makes me scratch my head twice. 

On a closer inspection while coding, we require more things from `KubernetesDiscoveryProperties`: [allNamespaces, namespaces, serviceLabels](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/7c73c5b941cfa2bc494edde44b49cb657f50611b/spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/catalog/KubernetesEndpointSlicesCatalogWatch.java#L60), so we can't move it.
