### ISSUE TITLE
Spring cloud override mockito.version  defined by SB

### ISSUE THREAD

**Issue by oburgosm** [spring-cloud/spring-cloud-kubernetes#1355]
Since spring cloud 2022.0.3, due to [this commit](https://github.com/spring-cloud/spring-cloud-kubernetes/commit/0510e0eb5cbdd47edd7da911daf970e5627b8872), mockito version used by an application based on spring boot is not version defined in spring-boot-dependencies, because it is overriden by mockito-4.8.1

**Comment by spencergibb** [comment]
Not sure what to do here. Spring Cloud 2022.0.3+ are compatible with boot 3.0.x and 3.1.x. Spring Boot upgraded mockito to 5 and we need the build to work with both. See [the comment](https://github.com/spring-cloud/spring-cloud-kubernetes/commit/0510e0eb5cbdd47edd7da911daf970e5627b8872#diff-e6dd92e2aa0221626d152f58b31d38b334d12d6942bd3488cba5953a4d7295ddR237-R241).

We probably have 2 options, move the dependency management out of spring-cloud-kubernetes-dependencies since to the root pom.xml or remove dependency management all together and rely on the version property for test dependencies. I'm leaning toward the former, what do you think @ryanjbaxter ?
