### ISSUE TITLE
config server default profile issue

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1616]
I am not sure if this is an issue or not, I want to get your input on this one.

Suppose we want to find properties for the "config server default profile" for an "account" source.

Also, let's suppose that our `account` configmap has this data:

```
.....
metadata:
  name: account
data:
  one = 11
  account-default.properties: |-
    one=1
```

At the moment, we will also get the data from `account-default.properties`, even if `includeDefaultProfileData=false`.

Is this expected? Or better, is this by design that you have in mind?

**Comment by ryanjbaxter** [comment]
OK we can debate about which one should override which...but I am fine with that behavior.

But to your question, yes we should read `account-default`.  The point of `includeDefaultProfileData` is to not include any default profile data in profile specific property sources.  For example if there was another data entry called `account-prod` I would not want/expect the `one` property included in that property source at all.

Since in this case we are talking about the `default` profile, then I would expect all default profile data to be included whether that comes from a data entry with or without `-default`.
