### ISSUE TITLE
No leaders elected

### ISSUE THREAD

**Issue by steven-sheehy** [spring-cloud/spring-cloud-kubernetes#206]
I'm seeing scenarios in my testing of leadership election where I have two pods and both of them are leaders or both of them are followers indefinitely. Below I'll focus on no leaders being elected. I'm not sure if it's my handling of OnFailedToAcquireEvent or that an event is not fired for every leader->follower and follower->leader transition. Note this is tested without the changes in [204](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/pull/204). This occurs when the leader has connectivity issues trying to read the configmap:

```
WARN  2018-07-03 17:01:05,021 [pool-4-thread-1] o.s.c.k.l.LeadershipController: Failed to acquire leadership with role='myapp' for candidate='myapp-6cfc568cc8-9bkvr': Operation: [get]  for kind: [ConfigMap]  with name: [leaders]  in namespace: [production]  failed.
INFO  2018-07-03 17:01:05,022 [pool-4-thread-1] c.f.e.s.l.LeaderElectionService: Transitioned to follower
WARN  2018-07-03 17:01:10,880 [pool-4-thread-1] o.s.c.k.l.LeadershipController: Failed to acquire leadership with role='myapp' for candidate='myapp-6cfc568cc8-9bkvr': Operation: [get]  for kind: [ConfigMap]  with name: [leaders]  in namespace: [production]  failed.
```

My listener class is below. By the way, it'd be nice if spring-cloud-kubernetes-leader provided a class with interface  `boolean isLeader()` that could be injected and handle below logic (and without an expensive kube-api call as in Context.isLeader()).
```java
public class LeaderElectionService {

	private volatile boolean leader = false;

	public boolean isLeader() {
		LOGGER.debug("Is leader: {}", leader);
		return leader;
	}

	@EventListener
	public void granted(OnGrantedEvent event) {
		leader = true;
		LOGGER.info("Transitioned to leader");
	}

	@EventListener
	public void revoked(OnRevokedEvent event) {
		leader = false;
		LOGGER.info("Transitioned to follower");
	}

	@EventListener
	public void failed(OnFailedToAcquireEvent event) {
		if (leader) {
			leader = false;
			LOGGER.info("Transitioned to follower");
		}
	}
}
```

So since the leader could not read the configmap for an extended amount of time, his leadership should be revoked. But there doesn't seem to be any mechanism to expire leaders in the configmap if they don't check-in within the lease duration. Later he is able to read the configmap but no event is fired to re-mark him as leader. I could remove my handling of OnFailedToAcquireEvent so he stays as leader, but then he won't transition to follower when someone else leader id is in the configmap and `if (candidate.getId().equals(leader.getId())` is false. Suggestions?

**Comment by gytis** [comment]
As it is implemented now, another pod can take over leadership only if the current leader's pod doesn't exist any more. This means that even if the current leader cannot access the configmap because of a connectivity issue it is still a leader.

The only issue I see here is that `OnFailedToAcquireEvent` is triggered when the configmap access fails even though this pod is a leader. It happens because we're not keeping any local state about the leadership and always rely on getting information from the confgimap. Having current implementation in mind, maybe we should stop contacting configmap for info as soon as pod becomes a leader?

As for your service, I think that you should only set `leader=false` when `OnRevokedEvent` is called.

**Comment by steven-sheehy** [comment]
Ok, I will remove watching `OnFailedToAcquireEvent`. As it is now it is pretty useless for leader to recheck every lease duration (30s) if he doesn't actually update anything. Plus only followers have responsibility to re-check status and possibly revoke leadership in current implementation. But keeping it is also not a heavy load on system either so not a big deal either way, just that spurious triggering of `OnFailedToAcquireEvent` you mentioned.

**Comment by steven-sheehy** [comment]
An advantage to not acquiring repeatedly if currently leader will be that it will help address #210 and acquire it once on startup, fire a `OnGrantedEvent` one time, then not schedule any more calls to `LeadershipController`.

**Comment by spencergibb** [comment]
@gytis can you review again?

**Comment by gytis** [comment]
This shouldn't be an issues since introduction of https://github.com/spring-cloud/spring-cloud-kubernetes/commit/ca80117f3590c9c6d3bac97419f5b30d195491f5#diff-8322b03d221fa577993ec51acbb43d83. Now when a leader is elected all followers create a readiness watcher for the leader's pod and try to take over leadership whenever leader becomes unresponsive.

Of course it would be great if @steven-sheehy could confirm the status of his issues with his reproducer.

**Comment by steven-sheehy** [comment]
@gytis Sorry, I haven't had time to confirm your change has addressed these bugs. I will close them and reopen if still an issue later.
