### ISSUE TITLE
NullPointerException in KubernetesCatalogWatch

### ISSUE THREAD

**Issue by stefan-hudelmaier** [spring-cloud/spring-cloud-kubernetes#223]
`
java.lang.NullPointerException: null
	at org.springframework.cloud.kubernetes.discovery.KubernetesCatalogWatch.lambda$catalogServicesWatch$2(KubernetesCatalogWatch.java:65) ~[spring-cloud-kubernetes-discovery-0.3.0.RELEASE.jar!/:0.3.0.RELEASE]
`

The problem seems to be that both `Addresses` and `TargetRef` may be null (as is the situation in our k8s cluster for some endpoints).

I will provide a PR for your consideration.

**Comment by fromlabs** [comment]
@stefan-hudelmaier your fix works for me but I've another case. I have ServiceA that calls ServiceB, and occasionally, during a graceful ServiceB shutdown, ServiceA throws a NPE because getSubsets may be null. I'm experimenting on Google Kubernetes Engine with a cluster of preemptible instances so shutdown are called almost once a day.
