### ISSUE TITLE
ConfigMap is not loaded from mounted volume

### ISSUE THREAD

**Issue by Lex4hex** [spring-cloud/spring-cloud-kubernetes#327]
Hello! 

spring-cloud-kubernetes-config version is 1.0.0. 
It wasn't an issue on 0.3.0.

I'm trying to load *.properties file from mounted volume: 

```volumeMounts:
            - mountPath: "/config-volume/"
              name: config-volume
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: example-volume-file-configmap
            items:
              - key: example.application.properties
                path: example.application.properties
```

My bootstrap.yaml: 

``` spring:
  profiles: volume-config-profile
  cloud:
    kubernetes:
      config:
        paths: "/config-volume/" 
```
  
Kubernetes creates a symlink to `example.application.properties` in `/config-volume` directory. 
But in this commit  https://github.com/spring-cloud/spring-cloud-kubernetes/commit/a006296c780df21cc899690c1545747b9d934168#diff-61a318ccc3b341cb8a04969cbc5961db @geoand added a filter for regular files `.filter(Files::isRegularFile)` so it skips symlink to my properties file.

**Comment by geoand** [comment]
Hey @Lex4hex 

The intention there was to skip directories, so I would consider this a bug.
If you have some time to spare and would like to work on a fix that would be great :)

If not, I can handle it a few days

**Comment by Lex4hex** [comment]
@geoand I'll fix it

**Comment by geoand** [comment]
Cool!

**Comment by iscra** [comment]
Hello,
I have just tracked my issue to the same problem here and went through all the associated comments. Yes, I have seen the notice in README, but interpreted it differently, as in "recursive is off" would mean subdirectories are not parsed, just the top one.

The issue is "spring.cloud.kubernetes.config.paths" must now have only files, never directories.

This is very inconsistent with how secrets work and not very usable.
I would have to list all property keys for it to work, if I understand that now correctly.
This is simply not feasible and not possible in my use case as I don't know which config will be defined for different kubernetes namespaces / staging environment - this happens in deployment.
I suppose it works just for the use case, when the properties are embedded again as full file under one key, so it's kind a workaround then.

Please support reading configmaps from files same as secrets, as it was before. If necessary this could be configured as another config option. All the code is still there used by secrets, just need to enable it.

**Comment by geoand** [comment]
Hello,

What you describe was intentionally removed as an option.
It was removed because discovering files that maybe configuration files in arbitrary depths can make things very unpredictable.
I don't remember why it hasn't been done for secrets yet, but the comments in the issues /PRs should provide an answer.
