### ISSUE TITLE
Can KubernetesCatalogWatch be able to watch k8s endpoint events between list () gaps?

### ISSUE THREAD

**Issue by toyangdon** [spring-cloud/spring-cloud-kubernetes#438]
Such as the mechanism of Reflector in k8s client-go,Periodic execution of ListerWatcher, Lister can get all the endpoints, Watcher can get the increment of endpoints(changes).  
In this way, endpoint changes can be updated in real time.

**Comment by TYsewyn** [comment]
I'm not sure if I fully understand your question but if you're asking if `KubernetesCatalogWatch` can be used to get notified if an endpoint has changed than the answer is yes, because it already does that. The `KubernetesCatalogWatch` will retrieve the endpoints and its subsets and will send out an event in case something has changed since the last time it checked the endpoints/subsets.
It will do that by default every 30 seconds, but you can configure its time interval with `spring.cloud.kubernetes.discovery.catalogServicesWatchDelay`.

**Comment by toyangdon** [comment]
Kube Apiserver provides a watch interface, a way of long connection, by which the server pushes endpoint changes.    
Is it possible to use this mechanism:  
First, get all  endpoints from apiserver , then call the watch interface to establish a long connection, and get the incremental change of endpoint in real time. At the same time, get  all endpoints from apiserver every 5 minutes for synchronization.

**Comment by fengchenghu** [comment]
> Kube Apiserver provides a watch interface, a way of long connection, by which the server pushes endpoint changes.
> Is it possible to use this mechanism:
> First, get all endpoints from apiserver , then call the watch interface to establish a long connection, and get the incremental change of endpoint in real time. At the same time, get all endpoints from apiserver every 5 minutes for synchronization.


Has it been achieved?
