### ISSUE TITLE
what is the best practice for spring cloud kubernetes with istio

### ISSUE THREAD

**Issue by zzzhy** [spring-cloud/spring-cloud-kubernetes#488]
Recently, our team are intended to using istio for service mesh...
But the projects are in spring cloud arch, so what's the best practise to integrate istio and spring cloud kubernetes ?
I mean using more the cloud native componets such as service discovery (whereas ribbon)...

**Comment by livelyRyan** [comment]
I'm doing spring cloud kubernetes and istio integration, but I have a problem

I have configured two versions of an application to distribute in the direction of 100:0. However, when I access the service, the two versions will alternately display, that is, the configured traffic rules are not effective, and the current is polling. I suspect that the reason is that after the client load balancing of ribbon, the specific pod is accessed directly through the pod IP, so the policy of istio is not effective.

By https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.0.M2/reference/html/#_ribbon_discovery_in_kubernetes,i configured spring.Cloud.Kubernetes.Ribbon.Mode = service, but it didn't work

Have you ever had this problem?


-------------------------------------
我正在做spring-cloud-kubernetes和istio整合的事情,但是我遇到了一个问题.

我配置了一个应用的两个版本,以100:0进行流向分发.但是当我访问该服务时,两个版本会交替显示,即配置的流量规则没有生效,当前是轮询. 我怀疑是因为ribbon的客户端负载均衡后,通过pod ip直接指定访问特定pod了,因此istio的策略没有生效. 

通过官网说明https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.0.M2/reference/html/#_ribbon_discovery_in_kubernetes,我配置了spring.cloud.kubernetes.ribbon.mode=SERVICE,但是并没有生效.

你是否有遇到过这个问题?

**Comment by zzzhy** [comment]
@livelyRyan 我用openfeign直接指定url的域名没有问题

**Comment by TYsewyn** [comment]
Please take a look at [this talk](https://www.youtube.com/watch?v=AMJQO9zs2eo) which goes a little bit more in detail as to what to use when.

**Comment by zzzhy** [comment]
@TYsewyn thanks for the video, but it seems not the one I wanted.
I prefer this framework can cooperation with istio well by visiting the services while not directly to the pods.

**Comment by TYsewyn** [comment]
Then you want to disable/exclude service discovery in/from your application and just use dns resolving.

**Comment by zzzhy** [comment]
that's right. no others but just kubernetes' service discovery ability.
exactly spring boot + k8s + istio.  but on this Collocation, the chain is block if kubernetes' service names not equals to module names.
now my solution is use spring boot , but the appliction name equals to kubernetes' service name, and then use rest requests route to the services by dns resolving.
this is not a quite good solution but it works fine.
greatly hope to find a better way.

**Comment by zzzhy** [comment]
in case of not contains too much resttemplate codes, I use openfeign either

**Comment by TYsewyn** [comment]
You can create your own routing/traffic management using virtual services with Istio, which you will definitely need if you want to support eg. resiliency, A/B testing, or other types of load balancing.
This way you can route `https://my-app-name` to the K8s service `my-app-service` so you don't need to change anything in your code.
The only thing you need to do is set the url in the `@FeignClient` annotation (you can use placeholders for that if you wish) and disable service discovery in your externalized configuration with `spring.cloud.discovery.enabled=false`.

Since it looks to me that you should look at Istio in more detail, I'm going to close this issue.
