### ISSUE TITLE
Clarify disabling Kubernetes features

### ISSUE THREAD

**Issue by TYsewyn** [spring-cloud/spring-cloud-kubernetes#510]
Hi, this is a `first-timers-only` issue. This means we've worked to make it more legible to folks who either haven't contributed to our codebase before, or even folks who haven't contributed to open source before.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

If you have contributed before, consider leaving this one for someone new, and looking through our general `ideal-for-contribution` issues. Thanks!

# Problem
The docs are unclear about how to disable Spring Cloud Kubernetes features, or all together, when `spring-cloud-kubernetes-config` is on the classpath.

See #478, #492

# Solution
The documentation resides under `docs/src/main/asciidoc`.
`kubernetes-awareness.adoc` already mentions how to disable Spring Cloud Kubernetes, but isn't more specific where to specify this.
This paragraph should be extended with the explanation that this property should be added to `application.{properties|yml}`, or the profile specific one, and when `spring-cloud-kubernetes-config` is on the classpath to put it in `bootstrap.{properties|yml}`, or the profile specific one.
Ideally, this paragraph also mentions that `spring.cloud.kubernetes.config.enabled` and `spring.cloud.kubernetes.secrets.enabled` can only have impact when set in `bootstrap.{properties|yml}` or the profile specific one.

# Steps to Fix
- [x] Claim this issue with a comment below and ask any clarifying questions you need
- [ ] Set up a repository locally following the [Contributing Guidelines](https://github.com/spring-cloud/spring-cloud-kubernetes#contributing)
- [ ] Try to fix the issue following the steps above
- [ ] Commit your changes and start a pull request.

**Comment by TYsewyn** [comment]
Claimed by @akuma8 via https://github.com/spring-cloud/spring-cloud-kubernetes/issues/492#issuecomment-569896316

**Comment by akuma8** [comment]
Hi @TYsewyn 
I set up my local repository. I had to install `Asciidoctor` since I never used it before. 
I clone 2 repositories [(1) Spring Cloud Kubernetes](https://github.com/spring-cloud/spring-cloud-kubernetes) and [(2) Spring Cloud Build]( https://github.com/spring-cloud/spring-cloud-build). 
To install dependencies locally, I did a simple `mvn clean install` on the (2) project but it fails with this error: 

`Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (default-resources) on project spring-cloud-build-docs: D:\Open Source Contributions\Spring Cloud\spring-cloud-build\docs\target\classes\asciidoc\index.adoc: Le client ne dispose pas d’un privilège nécessaire.
`

The error message is in french. I think I have some permission issues. 
I know this is not a problem for this task but if you have any suggestion or already had the same issue, please let me know.

I hope to open the PR tomorrow.

**Comment by TYsewyn** [comment]
Hi @akuma8! Thanks for the PR!
For future PRs: you shouldn't need to build `spring-cloud-build` locally unless you want to make changes in that project. Otherwise you can just download that dependency from maven central :)
