### ISSUE TITLE
KubernetesDiscoveryClient not registered with DiscoveryClientHealthIndicator

### ISSUE THREAD

**Issue by an1310** [spring-cloud/spring-cloud-kubernetes#517]
**Describe the bug**
I've encountered an interesting issue where the KubernetesDiscoveryClient is being instantiated and working for Kubernetes service discovery, yet it is never registered with the DiscoveryClientHealthIndicator.

The chain of events are as expected: https://cloud.spring.io/spring-cloud-static/Greenwich.SR4/single/spring-cloud.html#_health_indicator
- The DiscoveryClientHealthIndicator is created with a DependencyObjectProvider (Order.HIGHEST_PRECIDENCE)
- The KubernetesDiscoveryClient is created.
- The CompositeDiscoveryClient is created with instances of the SimpleDiscoveryClient and the KubernetesDiscoveryClient.

However, the DiscoveryClientHealthIndicator's onApplicationEvent callback is never called.  On inspection, I can see the ObjectProvider discoveryClient correctly references the CompositeDiscoveryClient.

The end result is the health indicator for the client is reported as "UNKNOWN".

Digging further, I see there are only two places where the expected InstanceRegisteredEvent could be called, but neither of these seem to be invoked:

AbstractAutoServiceRegistration
KubernetesAutoServiceRegistration (marked as deprecated)

Observed on: Spring Cloud Greenwich.SR4

**Comment by spencergibb** [comment]
Can you try with hoxton?

**Comment by fehmer** [comment]
Hi @spencergibb , I am able to reproduce this issue with Hoxton.SR3.

**Comment by patpatpat123** [comment]
Hello @spencergibb @fehmer @an1310,

Reproduced the exact same with Springboot 2.4.0 + Ilford M6

What can I do to help on this issue please?

Thank you

**Comment by ryanjbaxter** [comment]
@patpatpat123 if you want to help fix the issue you can submit a PR with your proposed changes and reference this issue.

**Comment by patpatpat123** [comment]
Hello @ryanjbaxter,

I do want to give this a try.
However, I would say I am more of a happy user of spring-cloud-kubernetes rather than who understands its architecture and design.

But I am interested! Is it possible to point me to what classes/packages should I look for?
Also, I do not know yet what is the root cause and what might even be causing this.
Is it possible to provide some references/pointers please? Something such as "the class X in this package Y is reading a null value from this place Z, fix this and the discovery will work".

I do want t give this a try.
Thanks!

**Comment by ryanjbaxter** [comment]
I would start with `KubernetesClientHealthIndicator` and see where that gets you.

**Comment by wtthetop** [comment]
Hello @ryanjbaxter ,
I found that the problem is because of a deprecated class  `KubernetesAutoServiceRegistration`. 
Before that this class will publish an `InstanceRegisteredEvent`. When i manually publish this event, this problem is solved.
So I want to ask, On which class can I edit and to publish this event?

**Comment by ryanjbaxter** [comment]
I dont see `KubernetesAutoServiceRegistration` actually being used anywhere.  Where did you see it actually being used?

**Comment by wtthetop** [comment]
Sorry I dont found it being used anywhere. But by manually publish the `InstanceRegisteredEvent`, the problem is solved.
Maybe we can add a method to publish this event in some places？

**Comment by patpatpat123** [comment]
Many thanks guys for your inputs.

I am having a hard time troubleshooting this.

Much appreciated

**Comment by ryanjbaxter** [comment]
OK I see.  I a unsure what the right thing to do here is because it is Kubernetes controlling the number of instances that are running.  IDK if this is something we can "watch" and fire an event for.
