### ISSUE TITLE
How can I use ribbon to discovery endpoints in all namespaces?

### ISSUE THREAD

**Issue by shinji3887** [spring-cloud/spring-cloud-kubernetes#573]
if I use discovery client , I can use 
```
spring.cloud.kubernetes.discovery.all-namespaces=true
```
to discover all the services in k8s，but ribbon can only find endpoints in the **current namespace**
I think this issue is similar to https://github.com/spring-cloud/spring-cloud-kubernetes/issues/505
another question is , why ribbon discovery has been removed since 1.1.3.RELEASE? I think this feature is quite useful to me.
pls help me.

**Comment by piomin** [comment]
Yes, the change you mentioned #505 has been avoided since Ribbon is going to be removed in the next next versions of Spring Cloud. Currently there is open PR #562 for adding Spring Cloud Load Balancer. If Spring Cloud Team accept it you would be able to use spring.cloud.kubernetes.discovery.all-namespaces=true feature since Spring Cloud Load Balancer is based on discovery client directly (spring-cloud-kubernetes-ribbon no). Until they merge my PR you may use solution I described here #571

**Comment by shinji3887** [comment]
> Yes, the change you mentioned #505 has been avoided since Ribbon is going to be removed in the next next versions of Spring Cloud. Currently there is open PR #562 for adding Spring Cloud Load Balancer. If Spring Cloud Team accept it you would be able to use spring.cloud.kubernetes.discovery.all-namespaces=true feature since Spring Cloud Load Balancer is based on discovery client directly (spring-cloud-kubernetes-ribbon no). Until they merge my PR you may use solution I described here #571

thx for your reply! I have sovled this problem by using codes in this PR https://github.com/spring-cloud/spring-cloud-kubernetes/pull/507
And I want to know the roadmap about **client discovery**. If the community want to use **Spring Cloud Load Balancer** instead of **Ribbon**, is it possible to discovery endpoints across all the namesapces with Spring Cloud Load Balancer?

**Comment by piomin** [comment]
Currently, you would have just to include spring-cloud-starter-loadbalancer into your dependencies and disable Ribbon. Because it is based directly on the implementation of DiscoveryClient it should work for you since there is KubernetesDiscoveryClient available on the classpath, and it supports discovery across all namespaces

**Comment by ryanjbaxter** [comment]
The documentation can be found here https://docs.spring.io/spring-cloud-kubernetes/docs/1.1.6.RELEASE/reference/html/#loadbalancer-for-kubernetes
