### ISSUE TITLE
Need some clarification on integrated reload feature deprecation

### ISSUE THREAD

**Issue by userlabs** [spring-cloud/spring-cloud-kubernetes#662]
Recently, the reload feature was deprecated "This functionality has been deprecated in the 2020.0 release. Please see the Spring Cloud Kubernetes Configuration Watcher controller for an alternative way to achieve the same functionality." 

I can see some decoupling or separation of concerns here.. but any other specific reason this was deprecated - trying to understand any limitations with respect to the original feature implementation or k8s APIs.

**Comment by userlabs** [comment]
Any updates?

**Comment by ryanjbaxter** [comment]
The reason to deprecate it is because we want to remove from having applications rely on needing to use the K8S API directly.  By removing the reload functionality from the app itself and centralizing it in a controller you can deploy, it allows the same functionality without needing to give the app permissions to use the K8S API.

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
