### ISSUE TITLE
Add ability to configure a list of "primary-port-name"s

### ISSUE THREAD

**Issue by tsalm-pivotal** [spring-cloud/spring-cloud-kubernetes#733]
**Is your feature request related to a problem? Please describe.**
Discovery of services with multiple port definitions currently leads to NullPointerException if `spring.cloud.kubernetes.discovery.primary-port-name` not set see reported issue [here](https://github.com/spring-cloud/spring-cloud-kubernetes/issues/731). It's only possible to fix this if all services with more than one port have the same port name and that is for example with system-provided services in the kube-config namespace not easy to achieve.

**Describe the solution you'd like**
Ability to configure a list of "primary-port-name"s and adding a meaningful error message to the IllegalStateException [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-client-discovery/src/main/java/org/springframework/cloud/kubernetes/client/discovery/KubernetesInformerDiscoveryClient.java#L134)

**Comment by tony-clarke-amdocs** [comment]
I am having the exact same experience. It's kind of unusable in its current state. Are we missing something?

**Comment by TYsewyn** [comment]
**Proposal**
Label the service with a `primary-port-name` key and desired port name as value.

Steps:

1. In case there are multiple ports, first check if there's a `primary-port-name` label and fall back to `spring.cloud.kubernetes.discovery.primary-port-name` being the generic setting for all services.
Log an error with a meaningful error in case there's no primary port name defined.
2. Find the port using the discovered port name in step 1.
Log an error with a meaningful error in case there's no port found.

In both steps I'd favor logging an error message instead of throwing an `IllegalStateException`.
Because this is runtime configuration (both application and Kubernetes environment) this could potentially cause a crash loop when something has been misconfigured.

**Comment by wind57** [comment]
there is a little nitpick surrounding this issue: this is not documented in the docs. I'll do that in one of my PRs.
