### ISSUE TITLE
Ability to refresh configuration of Spring Cloud app when multiple configmaps get changed 

### ISSUE THREAD

**Issue by iulianm82** [spring-cloud/spring-cloud-kubernetes#740]
Hi,

Does Spring Cloud Kubernetes Configuration Watcher support having an application running onto a kubernetes pod be notified after multiple configmaps were changed?
As my configmaps have different names, is there a way to have them linked to my app? Basically, I would need to work around the rule of configmaps and my application having the same name (which is obviously not possible, as one application can have only one name, right?).

The current approach of achieving what I described above it by using a list of sources, as decribed at this [link](https://docs.spring.io/spring-cloud-kubernetes/docs/2.0.0-M3/reference/html/#kubernetes-propertysource-implementations), but this support will be deprecated in future versions and, I guess, eventually removed.

If there currently linking multiple configmaps to the same application is not supported, is there any plan to add it in the future?

Thanks,
Iulian

**Comment by ryanjbaxter** [comment]
Good feature request....no it is not possible at the moment, but we could do something similar to what we do with non-default actuator paths and ports.  Maybe add an annotation to the configmap/secret that specifies the application name?

For example, `boot.spring.io/application-name`.

**Comment by iulianm82** [comment]
Thanks.
Could you please keep the current support of using list of sources at least until you add the support we discussed above in Configuration Watcher? We are currently using list of sources to link multiple configmaps to our application. It's OK if you deprecate it in a future version, like I read on another thread.
Based on your answer, we'll know whether we need or not do something within our software. Thanks!

**Comment by ryanjbaxter** [comment]
It won't be removed until our next major release, and yes we will add support for this before that happens.

**Comment by bilak** [comment]
@ryanjbaxter hello is there any plan to develop this feature request? We are planning to integrate configuration watcher in our cluster and we also need to watch multiple configmaps/secrets. Thanks

**Comment by ryanjbaxter** [comment]
Yes it is something I want to work on.  If you have any interest in helping out we always welcome contributions from the community!

**Comment by bilak** [comment]
@ryanjbaxter I can help with that I think we can benefit from that also, but we should agree whether what I mean is sufficient.

Currently application vs configmap is resolved only by configmap name [http watcher example here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/HttpBasedConfigMapWatchChangeDetector.java#L115). 

```
rotected Flux<ResponseEntity<Void>> refresh(ObjectMeta objectMeta) {

		return kubernetesReactiveDiscoveryClient.getInstances(objectMeta.getName()).flatMap(si -> {
```
We can extend that and add some labels or annotations. The problem is that labels and annotations ar simple key value (string:string). So we have two options:
* **prefix** for example `spring-app-{appname}: true`. In this case we will be able to simply enable/disable some of applications to be notified about changes without actually removing the appname from configmap. 
* **property with values separated by comma**  something like `spring-additional-apps: app1,app2,...`

In both cases prefix or property name should be configurable like `spring.cloud.kubernetes.configuration.watcher.configLabel` or `spring.cloud.kubernetes.configuration.watcher.secretLabel`

I prefer the later (property separated by coma) because at least it looks like some list. 

Last thing which I don't know is do we need to somehow modify also [ConfigMapWatcherChangeDetector#isSpringCloudKubernetesConfig](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-controllers/spring-cloud-kubernetes-configuration-watcher/src/main/java/org/springframework/cloud/kubernetes/configuration/watcher/ConfigMapWatcherChangeDetector.java#L78)?

**Comment by ryanjbaxter** [comment]
I think option 2 is the best approach.

> Last thing which I don't know is do we need to somehow modify also ConfigMapWatcherChangeDetector#isSpringCloudKubernetesConfig?

No I don't think so.  That still needs to be in place.

**Comment by madboynatesh** [comment]
Hi @iulianm82 
**The current approach of achieving what I described above it by using a list of sources, as decribed at this [link](https://docs.spring.io/spring-cloud-kubernetes/docs/2.0.0-M3/reference/html/#kubernetes-propertysource-implementations), but this support will be deprecated in future versions and, I guess, eventually removed.**
I was trying out the approach in the above mentioned link with multiple config-maps, but seems like it refreshes only the properties from configmap named with application-name. Any luck here to make it work?
Also @ryanjbaxter In spring-cloud-kubernetes-config-watcher, is there a way to provide different reload strategies which we have in [propertysource-reload](https://docs.spring.io/spring-cloud-kubernetes/docs/2.0.0-M3/reference/html/#propertysource-reload).

Thanks.

**Comment by ryanjbaxter** [comment]
@madboynatesh yes, you would have to set the property as an environment variable in the deployment of the config-watcher

**Comment by Nirvandil** [comment]
Hello. I need this feature too. 
I'm trying to get services load ConfigMaps with name as spring convention for profiles-specific properties, e.g. application "myApp" should load CMs "myApp", and when it runs with active profile "debug" also should load properties form CM "myApp-debug". I can achieve loading properties, but can't get properties refreshed with Spring Cloud Kubernetes Configuration Watcher, because it will send "/refresh" requests only when CM "myApp" changes and will completely ignore "myApp-debug" changes.

**Comment by wind57** [comment]
I'd like to take this issue and work on it. 

imho, we should be able to let users "opt-in" into this feature, so that it does not break existing apps. As such, here is my proposal:

- if you define a config map with label `spring.cloud.kubernetes.config/spring.cloud.kubernetes.secret=true`, it means one of the two things:

- if it does _not_ have the `spring.cloud.kubernetes.config.apps/spring.cloud.kubernetes.secret.apss` - we will refresh based on name of the source.

- if it does have the above property we will refresh based on the provided apps.


@ryanjbaxter if you agree with the above approach I will be glad to work on this one.

**Comment by ryanjbaxter** [comment]
Sounds good to me

**Comment by wind57** [comment]
while trying to implement this, I've hit a small problem. We can't have `spring.cloud.kubernetes.configmap.apps` as a label. There are two limitations:

- it's value must be less then 63 characters and we can easily reach that
- it can not contain `,`

As such, I will move this field to `data`. Something like:

```
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: example-configmap 
  labels:
    spring.cloud.kubernetes.config: "true"  
data:
  spring.cloud.kubernetes.configmap.apps: "spring-cloud-kubernetes-configuration-watcher-app-a, spring-cloud-kubernetes-configuration-watcher-app-b"
  
```

**Comment by ryanjbaxter** [comment]
Can you have multiple labels with the same name but different values?

**Comment by wind57** [comment]
nope, the last one will override all others.

**Comment by ryanjbaxter** [comment]
So can you have multiple data entries?

**Comment by wind57** [comment]
you do, but they are still key/value pairs. So something like this : 

```
data:
  spring.cloud.kubernetes.configmap.apps: 
    - spring-cloud-kubernetes-configuration-watcher-app-a 
    - spring-cloud-kubernetes-configuration-watcher-app-b
```
is not supported.

**Comment by next-gjimenez** [comment]
Maybe this mapping configuration can be defined in the Watcher configuration, not in each configmap. So, when Watcher detects a change in a configmap, it checks its own configuration. If there isn't any entry for that configmap name, it emits an event by the bus to an application with the same name as the configmap. But in this Watcher config you could map for example the target application name (so the app can have different name than configmap), or event map a configmap to more than one application.

What do you think? Does it make sense?

**Comment by demaryhuerto** [comment]
Maybe this mapping configuration can be defined in the Watcher configuration itselft, not in each configmap. So, when Watcher detects a change in a configmap, it checks its own configuration. If there isn't any entry for that configmap name, it emits an event by the bus to an application with the same name as the configmap. But in this Watcher config you could map for example the target application name (so the app can have different name than configmap), or event map a configmap to more than one application.

What do you think? Does it make sense?

**Comment by wind57** [comment]
in this case, watcher has to be restarted (manually or reload itself) whenever a service enters or leaves your domain. 

I do not see any issue to map that like I showed above in the `data`, but I'll wait for Ryan to comment more; may be he sees a shortcoming here.

**Comment by ryanjbaxter** [comment]
I am just trying to understand what it looks like to also have data for the properties in the config map/secret.  Will the property source in the client application also have a property called `spring.cloud.kubernetes.configmap.apps`?

Does the data section now look like this for example?

```
data:
  spring.cloud.kubernetes.configmap.apps: "spring-cloud-kubernetes-configuration-watcher-app-a, spring-cloud-kubernetes-configuration-watcher-app-b"
  foo: bar
  hello: world
```

**Comment by wind57** [comment]
exactly right!

**Comment by ryanjbaxter** [comment]
What about using annotations?  They seem much more flexible and actually seems like the correct place for this information.

IMO this information is metadata about the config map/secret not information that should be propagated to the client.

**Comment by wind57** [comment]
sorry, forgot to comment here. I agree with the annotations approach and it makes sense.

**Comment by wind57** [comment]
The PR is out for review [here](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1067). 

I just want to put it for visibility here that we will delay the event posting, based on `spring.cloud.kubernetes.configuration.watcher.refreshDelay`, that by default is `120000` milliseconds. For some people, this might be too much, in such cases the watcher image can be configured with a different value:

```
      containers:
        - name: spring-cloud-kubernetes-configuration-watcher
          image: docker.io/springcloud/spring-cloud-kubernetes-configuration-watcher
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CLOUD_KUBERNETES_CONFIGURATION_WATCHER_REFRESHDELAY
              value: 100
```

**Comment by ryanjbaxter** [comment]
That default delay value is the max delay that Kubernetes has between the time the change is made in the Config Map/Secret and the time the value is updated in the mounted volume in the pod.  If you shorten it, there is no guarantee that the value will be updated in the mounted volume when the refresh event comes.

**Comment by ryanjbaxter** [comment]
This defeats the purpose of the configuration watcher.  The configuration watcher was introduced so that applications can refresh the application context when a config map or secret changes.  Kubernetes provides everything else you need via volume mounts.  

If you are going to use the Kubernetes API directly within the application then there is no point in using the configuration watcher as the application context will be refreshed if you set `spring.cloud.kubernetes.reload.enabled=true`

**Comment by wind57** [comment]
> That default delay value is the max delay that Kubernetes has between the time the change is made in the Config Map/Secret and the time the value is updated in the mounted volume in the pod. If you shorten it, there is no guarantee that the value will be updated in the mounted volume when the refresh event comes.

Was not aware of this, now it makes a lot more sense. thank you Ryan

**Comment by demaryhuerto** [comment]
> This defeats the purpose of the configuration watcher. The configuration watcher was introduced so that applications can refresh the application context when a config map or secret changes. Kubernetes provides everything else you need via volume mounts.
> 
> If you are going to use the Kubernetes API directly within the application then there is no point in using the configuration watcher as the application context will be refreshed if you set `spring.cloud.kubernetes.reload.enabled=true`

ummm, well, I was using Kubernetes API to read ConfigMaps, and to reload them. But according to the documentation, the reloading feature has been deprecated, proposing the Watcher... So I am moving just the reloading part... 

If the realoding feature (with Kubernetes API) is not removed in future releases... I would continue to use it (rather than Watcher), unless there is a problem with it that I don't know... But in that case I would suggest to change the documentation to explain two different approachs (mounted volume + watcher / Kubernes API for read and reload), but with no deprecation...

**Comment by ryanjbaxter** [comment]
@demaryhuerto we are trying to have people rely less on the Kubernetes API and instead rely on what Kubernetes provides as a platform out of the box.

Kubernetes provides a way to inject configuration into the pod already, but lacks the ability to notify the app that the configuration has changed (which if functionality Spring Cloud users have come to expect).  The config watcher allows the app to not need to leverage the Kubernetes API directly and be notified when its configuration is changed and refresh the application context. 

The reason for deprecating usage of the Kubernetes API is to encourage people to rely less on using the Kubernetes API directly.

**Comment by demaryhuerto** [comment]
ok, understood, thank you very much for the explanation. In that case I will keep Kubernates API for both reading and reloading at the moment, and I will plan to move to Watcher + mounted volume. Thanks!
