### ISSUE TITLE
Clarify docs section "Using a ConfigMap PropertySource"

### ISSUE THREAD

**Issue by asaikali** [spring-cloud/spring-cloud-kubernetes#779]
The docs section at https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#configmap-propertysource
states 

> The default behavior is to create a Fabric8ConfigMapPropertySource based on a Kubernetes ConfigMap that has a metadata.name value of either the name of your Spring application (as defined by its spring.application.name property) or a custom name defined within the bootstrap.properties file under the following key: spring.cloud.kubernetes.config.name.

Can you clarify what bean gets created when using`spring-cloud-starter-kubernetes-client-config` without using the Fabric8 client.

Also it is helpful to add a callout that reminds the reader that beans must be marked with `@RefreshScope` for hot-reload to work maybe even explain the hot reload feature works with Spring  Cloud k8s.

**Comment by wind57** [comment]
I do not know about hot reload, but the first part of your question is now part of `main` branch - where we have documented what bean is created. To be honest, I do not know why that is needed, since it can change, but may be I miss something. 

I would also very much like (at least imho), to track these two things separately, so that we could close this one and potentially open a new one about hot reloading... I'll wait to see what Ryan thinks about this.

**Comment by ryanjbaxter** [comment]
We already mention `@RefreshScope` here https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/docs/src/main/asciidoc/property-source-config.adoc#propertysource-reload

**Comment by ryanjbaxter** [comment]
I agree
@asaikali what do you think?

**Comment by asaikali** [comment]
looks good to me.
