### ISSUE TITLE
Use of DiscoveryClientHealthIndicator AND ReactiveDiscoveryClientHealthIndicator

### ISSUE THREAD

**Issue by patpatpat123** [spring-cloud/spring-cloud-kubernetes#839]
Hello Spring Cloud Kubernetes Team,

I just wanted to raise a small issue, please feel free to screen and add your expertise.

Facts:
My app, a Spring WebFlux app, not MVC at all, non blocking at all, is deployed in Kubernetes.

I activate the liveness probe. The liveness probe shows the following:

```
 s.c.c.d.h.DiscoveryClientHealthIndicator : Error
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Service]  with name: [null]  in namespace: [abc]  failed.

r.ReactiveDiscoveryClientHealthIndicator : Error
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [list]  for kind: [Service]  with name: [null]  in namespace: [abc]  failed.
```

I paste the log for an error, to make things a bit more relevant. You can clearly see there are the use of both  **DiscoveryClientHealthIndicator** AND **ReactiveDiscoveryClientHealthIndicator**

The success will also use both.

Finally, this is reproducible with any Spring Webflux app deployed in Kubernetes.

May I ask why the use of ```DiscoveryClientHealthIndicator``` AND ```ReactiveDiscoveryClientHealthIndicator``` in a Spring Webflux app please?

Thank you.

**Comment by wind57** [comment]
as far as I am looking at the code, you are right. There is no way to say : "I only want the reactive discovery heath indicator", I mean there is no `@ConditionalOnClass(Mono.class)` for example (just an idea of what I mean). But may be this is by design and I am missing something here. Anyway, those two are not part of this project per-se, but part of `spring-cloud-commons`.

I can't tell you a proper solution and these are just my 0.02$. Let's wait for someone with more authority to chime in.

**Comment by wind57** [comment]
@ryanjbaxter imho, this one can be closed also

**Comment by ryanjbaxter** [comment]
Not sure I agree because the autoconfiguration containing this health indicator should only be enabled if there is a DiscoveryClient bean, in this case there shouldnt be.
https://github.com/spring-cloud/spring-cloud-commons/blob/c2a22346cde819971263c47b321a81a7908c4f40/spring-cloud-commons/src/main/java/org/springframework/cloud/client/CommonsClientAutoConfiguration.java#L57

@patpatpat123 
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by patpatpat123** [comment]
Hello @wind57, hello @ryanjbaxter,

Understood, let me try to provide a small project. 
Thank you for looking at this, because I did try the properties and still could see both errors at the same time.
