### ISSUE TITLE
Application fails to start on update from 2.0.3 to 2.0.4 if using spring-boot-starter-log4j2

### ISSUE THREAD

**Issue by manderson23** [spring-cloud/spring-cloud-kubernetes#870]
I have an application using Spring Cloud K8s with a parent pom that declares spring-boot-starter-log4j2 as the dependency for logging.

Updating to 2.0.4 broke the application startup since spring-boot-starter-logging was a new dependency for Spring Cloud K8s. Could that be made optional? Or at least document that it should be excluded if you are using log4j2 with Spring Cloud K8s.

**Comment by wind57** [comment]
> broke the application startup

can you explain exactly how please? 

I am not sure we should be documenting this, we use various different dependencies internally for our project to work, if you interfere with that (and I do understand you might have good reasons for that), it's up to your project to correctly adjust.

I will wait for Ryan to chime in here also, but imho, this should not be documented.

**Comment by manderson23** [comment]
Failure to start at all with errors as follows since it tries to configure logback with the log4j2 configuration

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/application/BOOT-INF/lib/logback-classic-1.2.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/application/BOOT-INF/lib/log4j-slf4j-impl-2.14.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
Logging system failed to initialize using configuration from 'classpath:log4j2-production.xml'
java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.joran.spi.Interpreter@4:14 - no applicable action for [Appenders], current ElementPath  is [[Configuration][Appenders]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@5:48 - no applicable action for [Console], current ElementPath  is [[Configuration][Appenders][Console]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@6:103 - no applicable action for [PatternLayout], current ElementPath  is [[Configuration][Appenders][Console][PatternLayout]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@9:12 - no applicable action for [Loggers], current ElementPath  is [[Configuration][Loggers]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@10:24 - no applicable action for [Root], current ElementPath  is [[Configuration][Loggers][Root]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@11:34 - no applicable action for [AppenderRef], current ElementPath  is [[Configuration][Loggers][Root][AppenderRef]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@13:84 - no applicable action for [Logger], current ElementPath  is [[Configuration][Loggers][Logger]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@14:79 - no applicable action for [Logger], current ElementPath  is [[Configuration][Loggers][Logger]]
ERROR in ch.qos.logback.core.joran.spi.Interpreter@15:69 - no applicable action for [Logger], current ElementPath  is [[Configuration][Loggers][Logger]]
```

**Comment by Saljack** [comment]
I have the same problem. I did not find any way how to exclude `spring-boot-starter-logging` from imported bom so I have to update all our applications and put there exclusions:
```xml
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-kubernetes-fabric8-all</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

**Comment by wind57** [comment]
@manderson23 I took some time to figure out what is going on and here are my conclusions. 

In `spring-cloud-kubernetes` we use [spring-boot-starter-logging](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-starters/spring-boot-starter-logging/build.gradle) that declares three dependencies:

 - `ch.qos.logback:logback-classic`, which does the actual work
 - `org.apache.logging.log4j:log4j-to-slf4j`, which is a bridge into `slf4j`.
 - `org.slf4j:jul-to-slf4j`, same as above.

Since Spring uses `jcl` as the facade for logging, having the `spring-boot-starter-logging` means that `jcl` is going to find `logback` on the classpath and use that for logging. 

As far as I understand, the two bridges (`log4j-to-slf4j` and `jul-to-slf4j`) are needed in case there are components that use `log4j` and `jul` (jdk logging), but we want to "re-direct" their usage towards `logback`. Bridges in general don't have any meaningful code, all they do internally is redirect the calls to `slf4j`, while that in turn will find `logback` on the classpath and use that.

When you add [spring-boot-starter-log4j2](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-starters/spring-boot-starter-log4j2/build.gradle) dependency on the classpath, you add a different implementation than `logback`, specifically: `log4j-slf4j-impl`. Now there are two bindings on the classpath:

 - `logback-classic`
 - `log4j-slf4j-impl`

Obviously, `jcl` facade does not know which to choose, and fails.

---

I started looking where this dependency is coming from. So I ran : `grep -r "<artifactId>spring-boot-starter-logging</artifactId>" --exclude .flattened-pom.xml . | sort --unique | awk '{print $1}'`, As a result:

```
./spring-cloud-kubernetes-client-config/pom.xml:
./spring-cloud-kubernetes-commons/pom.xml:
./spring-cloud-kubernetes-fabric8-autoconfig/pom.xml:
./spring-cloud-kubernetes-fabric8-config/pom.xml:
```

All of them, _except_ `spring-cloud-kubernetes-commons/pom.xml` is declaring that dependency as `optional`. Aha! So this one is leaking it into the classpath of your project (this is exactly what `optional` is supposed to prohibit). Let's try and fix this locally first: declare the dependency `optional`, build the project, create a dummy gradle consumer that has :

```
dependencies {
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-log4j2', version: '2.5.5'
    // this one has fixed the leaking dependency with optional=true
    implementation 'org.springframework.cloud:spring-cloud-kubernetes-fabric8-autoconfig:2.0.5-SNAPSHOT'
}
```

Run a simple `@SpringBootApplication` and... :

```
Caused by: org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
```

Interesting. Issue `gradle dependencies`, analyze the output and notice that :

`spring-cloud-kubernetes-fabric8-autoconfig -> spring-boot-starter-json -> spring-boot-starter-logging`. Aha, one more transitive dependency. So we need to exclude this one now: 

```
<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-json</artifactId>
                         <!-- exclusion is safe, we already require this 
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

Build, run again - works.  So, I will be able to fix this.

It would be rather helpful if you would tell us where that dependency is leaking in your cases, may be I miss something.

**Comment by ryanjbaxter** [comment]
I'm trying to remember why I added this dep

https://github.com/spring-cloud/spring-cloud-kubernetes/commit/9b54b71872261a316f08f1b8009c3af7b50737a6

I think something changed in Spring Boot that required the change, but I can't remember exactly what it was :(

**Comment by ryanjbaxter** [comment]
Regardless making it optional seems reasonable

**Comment by wind57** [comment]
@ryanjbaxter this can be closed also

**Comment by Saljack** [comment]
@ryanjbaxter Hi this issue is presented in the latest version. So it was fixed only in 2021 and not in the latest 2022. Can we reopen it or create a new issue?

**Comment by wind57** [comment]
@Saljack did you try the latest 2022? I see if was backported there too.

**Comment by Saljack** [comment]
@wind57 Yes. It is visible here: https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-commons/pom.xml#L65

**Comment by ryanjbaxter** [comment]
Thanks @Saljack!  IDK how that change didnt make it in the pom :(
